### ISSUE TITLE
Add mev-boost

### ISSUE THREAD

**Issue by OisinKyne** [ObolNetwork/charon-distributed-validator-node#110]
# 🚀 Feature Request

## Problem to be solved

We want to show mev-boost use in the wild and we have no template repo for people, only some instructions. 

## Proposed Solution

Add mev-boost to this repo, along with instructions for creating the appropriate proposer config overrides for teku using their flags. 

Update any of the readmes + docs sites to reflect this extra proposer configuration if need be. 

Setup minimum two relay nodes, maybe neither of them flashbots to improve relay diversity. 

## Describe alternatives you've considered

Make a `charon-distributed-validator-mev-node` repo, but it seems like too much maintenance for now. 

## Out of Scope

Changes to the proposer auto registration stuff

**Comment by xenowits** [comment]
Solved by https://github.com/ObolNetwork/charon-distributed-validator-node/pull/159
