### ISSUE TITLE
Clean metrics as validator state changes

### ISSUE THREAD

**Issue by thomasheremans** [ObolNetwork/charon-distributed-validator-node#139]
# Problem to be solved
Currently the past activation states of a validator display in the `Charon Overview` dashboard as per the screenshot below. This is confusing as to the current states of the validators.

![Image](https://user-images.githubusercontent.com/107747791/204529679-2ea6bc7d-3cfd-473a-ba7a-d346da4aa1f9.png)

# Proposed Solution
- Only display the latest stage of the validators
- Note: It can happen that several deposits are made for the same validator and these should display as an increased balance (e.g. 64 ETH) or two separate lines

**Comment by xenowits** [comment]
Note that a simple workaround is to restart your charon node. This will clear the duplicates.
