### ISSUE TITLE
Replace `on-failure` with `unless-stopped`

### ISSUE THREAD

**Issue by xenowits** [ObolNetwork/charon-distributed-validator-node#144]
# 🚀 Feature Request

## Problem to be solved

Users have reported that some docker containers never restart when the machine reboots. This is expected as currently we have the `on-failure` restart policy.

To understand the difference between these two restart policies, see [here](https://stackoverflow.com/questions/61725195/difference-in-docker-restart-policy-between-on-failure-and-unless-stopped).

## Proposed Solution

Replace `on-failure` with `unless-stopped` restart docker policy in `docker-compose` files in the current repo. Also, do the same in the [cluster repo](https://github.com/ObolNetwork/charon-distributed-validator-cluster).

**Comment by Battenfield** [comment]
Thanks for creating! 🙏
