### ISSUE TITLE
Add support for opt-in builder-API

### ISSUE THREAD

**Issue by corverroos** [ObolNetwork/charon-distributed-validator-node#154]
# 🚀 Feature Request

## Problem to be solved

This repo doesn't allow easy configuration of mevboost but it will be most used option in prod.

## Proposed Solution

Add flags and stuff to overrides.yml. Also add documentation.

**Comment by thomasheremans** [comment]
**Story Points: 3**
  [See the discussion](https://action.parabol.co/meet/kTqTIeSZ2w/estimate/18) in Ongoing Sizing

  *Powered by [Parabol](https://www.parabol.co/resources/sprint-poker-meetings)*

**Comment by xenowits** [comment]
The associated PRs for this ticket are opened:
- https://github.com/ObolNetwork/charon-distributed-validator-node/pull/195
- https://github.com/ObolNetwork/obol-docs/pull/205 

Note that we're blocked on testing this as we need new clusters (with `config v1.7`) which supports pre-gen validator registrations. We can test and close this ticket after the merge.
