### ISSUE TITLE
Create the one line docker command that triggers Teku to broadcast an exit message

### ISSUE THREAD

**Issue by OisinKyne** [ObolNetwork/charon-distributed-validator-node#162]
# 🎯 Problem to be solved

Our existing exit process of dragging keys to a new folder and colliding docker network names is to hard for a certain set of our beginner users. I believe it is possible to do a `docker exec` command on a running VC (in this case the primary teku client with access to the key shares) to run the exit process we want. 

# Proposed solution

Figure out if there is a one-liner that can be done that executes the exit process on the running teku vc. 

- [ ] If there is, create an issue in obol-docs with the command and ask for an exit guide to be made
- [ ] Once made, we will delete the exit section from all the 4 existing guides, as part of our modularisation of these steps. 

# 🧪 Tests

- [x] Works in local docker-compose
- [ ] The guide docs have been user tested before being put live

# 👐 Additional acceptance criteria

# ❌ Out of Scope

**Comment by thomasheremans** [comment]
**Story Points: 3**
  [See the discussion](https://action.parabol.co/meet/kWT4FR7BVC/estimate/2) in Sizing - Protocol

  *Powered by [Parabol](https://www.parabol.co/resources/sprint-poker-meetings)*

**Comment by thomasheremans** [comment]
**Story Points: 2**
  [See the discussion](https://action.parabol.co/meet/kWTqq1fvxK/estimate/7) in Sizing - Platform

  *Powered by [Parabol](https://www.parabol.co/resources/sprint-poker-meetings)*
