### ISSUE TITLE
Add info to FAQ

### ISSUE THREAD

**Issue by xenowits** [ObolNetwork/charon-distributed-validator-node#17]
Add the following to the FAQ:
- Users should note that `charon enr`s can change each time. The ENR generated would not definitely match the ENR generated for the first time.
- Also, users should MANDATORILY BACKUP their `charon-enr-private-key` as soon as it is generated. Backup to a safe place like cloud storage. We can generate ENRs with the private key and hence private key is the most important.

**Comment by thomasheremans** [comment]
To retrieve private key: "It's in a hidden folder called .charon,  we didn't think that through so much. If you are on OSX you can press. Cmd + Shift + .   to view them, or in the CLI you can do ls -la to see hidden folders in your current directory, and cp .charon/charon-enr-private-key ~/Downloads to copy the key out to your downloads folder for easy access. On windows or linux this will be slightly different"
