### ISSUE TITLE
Test & Add Nimbus, Lighthouse VC exit command

### ISSUE THREAD

**Issue by thomasheremans** [ObolNetwork/charon-distributed-validator-node#181]
- [ ] Test that it exits successfully
- [ ] Add it to the docs
- [ ] Also add that the commands exit all validators at once

Design doc: [Link](https://docs.google.com/document/d/1EIIluSDhnof_7JI6Bg-37PfB3_lrmV7eYWTWV5hWLsw/edit#heading=h.vp9hz14xzu8g)

Commands suggested by RockawayX:
### Lighthouse
```
docker exec -ti charon-distributed-validator-cluster-vc3-lighthouse-1 /usr/local/bin/lighthouse --network goerli account validator exit --keystore /opt/charon/keys/keystore-0.json --password-file /opt/charon/keys/keystore-0.txt --beacon-node http://node3:3600 
```

### Nimbus
```
nimbus is something like this:
./nimbus_beacon_node deposits exit --validator=0x812534e29e1a21ec4d94d39671db4e8cec8757451d01038bc113b373ee0cd0574b856b7f635fc599c1cf31d615f3f2cc --rest-url=http://node5:3600/ --data-dir=/home/user/
```
but you should copy validators directory to /home/user/

**Comment by thomasheremans** [comment]
https://github.com/ObolNetwork/obol-docs/commit/03feeecad765e51e29a60a1cd76ff070a49a5c03

**Comment by sugh01** [comment]
Test Notes:

Lighthouse - 
Cluster - luki-charon-cluster
```shell
docker exec -ti charon-distributed-validator-node-lighthouse-1 /usr/local/bin/lighthouse --network goerli account validator exit \
--keystore /opt/charon/validator_keys/keystore-0.json \
--password-file /opt/charon/validator_keys/keystore-0.txt \
--beacon-node http://charon:3600/
``` 
The exit proceeds.
But the shell does not exit, keeps waiting - "Waiting for voluntary exit to be accepted into the beacon chain..." 
Do we need to mention this in the documents?

Nimbus -
