### ISSUE TITLE
Keep exotic test configs in folders

### ISSUE THREAD

**Issue by boulder225** [ObolNetwork/charon-distributed-validator-node#193]
**Context**
Current CDVN supports only 1 BN and 1 VC. Using devnet in pipeline, it is possible to test multiple BN<>VC combos in E2Es. 

**Problem**
How to use other BN <> VC combos in short term? Should any examples be shared in maybe /examples in CDVN?

**Proposed Solution**
Keep exotic test configs in folders (maybe namespaced as _development to make it obvious that these things should be used with caution)

**Comment by thomasheremans** [comment]
**Story Points: 5**
  [See the discussion](https://action.parabol.co/meet/kWT4FR7BVC/estimate/5) in Sizing - Protocol

  *Powered by [Parabol](https://www.parabol.co/resources/sprint-poker-meetings)*

**Comment by dB2510** [comment]
Closed by #199
