### ISSUE TITLE
Fix beacon node score panel

### ISSUE THREAD

**Issue by dB2510** [ObolNetwork/charon-distributed-validator-node#205]
# 🐞 Bug Report

### Description

Beacon node score panel in charon overview dashboard and single node dashboard shows `No data` while the expected behaviour is to show a non-negative percentage.

## 🔥 Error

![Screenshot 2023-06-14 at 3 05 52 PM](https://github.com/ObolNetwork/charon-distributed-validator-node/assets/37813203/b2a7d325-7c9c-4e67-a15e-7950e39368bd)
![Screenshot 2023-06-15 at 3 57 19 PM](https://github.com/ObolNetwork/charon-distributed-validator-node/assets/37813203/bef4f526-194f-4f29-aa09-1f3bdfab7997)

## 🌍  Your Environment

Prometheus version: v2.44.0
Grafana version: 9.5.3

**Anything else relevant (validator index / public key)?**

None

**Comment by boulder225** [comment]
**Story Points: 2**
  [See the discussion](https://action.parabol.co/meet/kWT4FR7BVC/estimate/4) in Sizing - Protocol

  *Powered by [Parabol](https://www.parabol.co/resources/sprint-poker-meetings)*
