### ISSUE TITLE
Lodestar produces full block and blinded block at the same time

### ISSUE THREAD

**Issue by dB2510** [ObolNetwork/charon-distributed-validator-node#206]
# 🐞 Bug Report

### Description

While testing builder api features with synthetic blocks in core team cluster, it has been found that lodestar asks for a full block and a blinded block at the same time. Then it checks `--builder.selection` flag before submitting signed block to beacon node. `--builder.selection` can be either **maxprofit** or **builderalways**. In maxprofit mechanism lodestar submits block which gives maximum rewards while in builderalways it always submits blinded beacon block.

## 🔬 Minimal Reproduction

Run a charon DV node with v0.17-dev and lodestar as validator client with builder API enabled.

## 🔥 Error

Error in charon service:
<pre><code>
ERRO vapi       Validator api 5xx response: builder-api enabled, but duty proposer requested {"status_code": 500, "message": "Internal server error", "duration": "28.086µs", "vapi_endpoint": "propose_block"}
</code></pre>

Error in Lodestar service:
<pre><code>
error: Failed to produce execution block  Failed to produce block: validator.produceBlockV2 - Internal Server Error: Internal server error
charon-distributed-validator-node-lodestar-1  | Error: Failed to produce block: validator.produceBlockV2 - Internal Server Error: Internal server error
charon-distributed-validator-node-lodestar-1  |     at Function.assert (file:///usr/app/packages/api/src/utils/client/httpClient.ts:44:13)
charon-distributed-validator-node-lodestar-1  |     at BlockProposingService.produceBlock (file:///usr/app/packages/validator/src/services/block.ts:289:18)
charon-distributed-validator-node-lodestar-1  |     at processTicksAndRejections (node:internal/process/task_queues:95:5)
</code></pre>

Note: Expected behaviour should be to always only ask and submit blinded block if `--builder.selection=builderalways`. Contact Lodestar team for the same.

**Comment by dB2510** [comment]
This issue is solved in lodestar in this PR: https://github.com/ChainSafe/lodestar/pull/5669. This change will be part of lodestar version v1.10.0. We need to add this flag to lodestar validator command: `--builder.selection=builderonly`.

**Comment by boulder225** [comment]
**Story Points: 1**
  [See the discussion](https://action.parabol.co/meet/kWT4FR7BVC/estimate/8) in Sizing - Protocol

  *Powered by [Parabol](https://www.parabol.co/resources/sprint-poker-meetings)*

**Comment by dB2510** [comment]
closed by #207
