### ISSUE TITLE
Lodestar builder selection error

### ISSUE THREAD

**Issue by samparsky** [ObolNetwork/charon-distributed-validator-node#209]
# 🐞 Bug Report

### Description

Lodestar is throwing an error with the builder selection

## 🔬 Minimal Reproduction

```
docker-compose up 
docker logs charon-distributed-validator-node-lodestar-1
```

## 🔥 Error

https://github.com/ChainSafe/lodestar/blob/unstable/packages/cli/src/cmds/validator/handler.ts#L261

That's the error being thrown

## 🌍  Your Environment

**Operating System:**

Linux (dappnode)

**What version of Charon are you running? (Which release)**

0.16

**Anything else relevant (validator index / public key)?**

**Comment by dB2510** [comment]
This issue is fixed in #211 . Closing this ticket as it is done.
