### ISSUE TITLE
Ensure CDVN is updated to the latest Charon release v0.17.0

### ISSUE THREAD

**Issue by boulder225** [ObolNetwork/charon-distributed-validator-node#218]
## 🎯 Problem to be solved
Launchnodes encountered an error while running the Docker Compose file for DV-alone, related to the cluster state and a JSON parsing error. The problem originated from an inconsistency between the cluster lock file version (v1.7.0) and the Docker Compose image version (v0.16.0). Subsequent discussions revealed a bug related to the registration timestamp JSON in v0.16, inconsistencies in versioning, and an overall lack of clarity in error messaging.

## 🛠️ Proposed solution
- [x] **Investigate Version Inconsistency**: Assess why the cluster lock file version and Docker Compose image version were mismatched, and how the incorrect timestamp format was released.
- [x] **Update CDVN**: Ensure that CDVN is updated to the latest Charon release v0.17.0, which includes the correct timestamp marshalling.
- [x] **Communicate with Launchnodes**: Direct them to update CDVN and run again, and check with them regarding the lock file and how it was generated.

**Comment by alansunny3** [comment]
this issue was resolved after updating the CDVN to the latest Charon release v0.17.0 and launchnodes pulling latest changes.
