### ISSUE TITLE
Parse cluster names to be alphanumeric only

### ISSUE THREAD

**Issue by boulder225** [ObolNetwork/charon-distributed-validator-node#224]
# 🎯 Problem to be solved
Grafana is breaking due to clusters having special characters in their names. This is particularly problematic as it affects monitoring and visualization. After a first analysis, cluster names can have special characters in names:

`charon create cluster --name="This is a string with special characters: \n (newline), \t (tab), \\ (backslash), \" (double quote), and \x41 (hex escape for 'A')." --withdrawal-addresses="0xC0404ed740a69d11201f5eD297c5732F562c6E4e" --fee-recipient-addresses="0xC0404ed740a69d11201f5eD297c5732F562c6E4e" --nodes=4 --threshold=3 --network=holesky --num-validators=5`

## 🛠️ Proposed solution
- [ ] Update validation rules for cluster name creation to restrict special characters.
- [ ] Update documentation to reflect the new naming constraints.

**Comment by OisinKyne** [comment]
Can we be a bit more flexible than only alphanumeric? I'd maybe do it by blacklisting things, e.g. whitespaces and quotations and stuff. Would be nice if we could be a little multi-lingual friendly, but if not, not the end of the world. If we don't have a max length on the field we should have one too tbh
