### ISSUE TITLE
Add a grafana panel for charon readiness

### ISSUE THREAD

**Issue by OisinKyne** [ObolNetwork/charon-distributed-validator-node#23]
# 🚀 Feature Request

## Problem to be solved

@xenowits added  readiness checks to prometheus (I think). We should expose this in a simple green/red box to indicate node readiness. 

## Proposed Solution

We should expose this in a simple green/red box to indicate node readiness. This will be a core feature for a user researcher like Chris to understand if a customer has successfully setup their node. If that green box is visible, it means their beacon client is connected and synced, and (a threshold or all(?)) of its peers are online.

## Describe alternatives you've considered

Doing the query by way of combining many other prometheus variables together with one fancy command. Doesn't sound clean and complete. 

## Out of Scope

Indicating/inferring counterparty peer health based upon their pings, and whether they are sending sigs.

**Comment by dB2510** [comment]
Closed by #21
