### ISSUE TITLE
Add an EL & CL docker-compose option

### ISSUE THREAD

**Issue by OisinKyne** [ObolNetwork/charon-distributed-validator-node#24]
# 🚀 Feature Request

## Problem to be solved

This  repo only runs on infura

## Proposed Solution

Setup a docker-compose that runs a non-geth EL and a non-prysm CL + DVC + DV

## Describe alternatives you've considered

 Have you considered any alternative solutions or workarounds?

## Out of Scope

 What do you consider to be beyond the scope of this ticket?

**Comment by dB2510** [comment]
Inspiration can be taken from: https://github.com/stereum-dev/ethereum2-docker-compose

**Comment by xenowits** [comment]
Why not run with geth? atleast for athena

I'm thinking of:
```yaml
- geth (EL)
- nimbus (BN)
- charon (DV)
- teku (VC)
```

**Comment by xenowits** [comment]
Resolved in https://github.com/ObolNetwork/charon-distributed-validator-node/pull/27
