### ISSUE TITLE
Check why Lighthouse validator exits are failing with Charon

### ISSUE THREAD

**Issue by boulder225** [ObolNetwork/charon-distributed-validator-node#251]
## 🎯 Problem to be solved
Lighthouse validator exits are failing with Charon, showing a "signature not verified" error. This issue persists even though the same keystore works with Teku. The problem might relate to the validator's private key not being recognized by Charon, or it could be due to an undocumented process for Lighthouse exits.

## 🛠️ Proposed solution
- [ ] Verify if the `keystore-1.json` used for signing the exit is listed in `cluster-lock.json`.
- [ ] Cross-check the public key in `keystore-1.json` against the pubshare in the lock file.
- [ ] Test the Lighthouse validator exit command on a core team node using Docker
- [ ] Check why voluntary exits with Lighthouse are not documented, and update the documentation if necessary.

**Comment by dB2510** [comment]
Hey team! Please [add your planning poker estimate](https://app.zenhub.com/workspaces/Obol-Workspace-648c1170ee94656741353327/issues/ObolNetwork/charon-distributed-validator-node/251?planning-poker) with Zenhub @dB2510 @gsora @pinebit @xenowits
