### ISSUE TITLE
Parameterize mev-boost image override ability in the Holesky sample configs  

### ISSUE THREAD

**Issue by boulder225** [ObolNetwork/charon-distributed-validator-node#268]
## 🎯 Problem to be solved
We need to parameterize the mev-boost image override ability in the Holesky sample configs to test it on the mainnet.

## 🛠️ Proposed solution

- [ ] Identify the existing Holesky sample configs that need to be modified
- [ ] Determine the best approach to parameterize the mev-boost image override (e.g., environment variables, configuration files)
- [ ] Implement the necessary changes to the Holesky sample configs to allow parameterization of the mev-boost image
- [ ] Document the process for overriding the mev-boost image in the sample configs

**Comment by boulder225** [comment]
Hey team! Please [add your planning poker estimate](https://app.zenhub.com/workspaces/Obol-Workspace-648c1170ee94656741353327/issues/ObolNetwork/charon-distributed-validator-node/268?planning-poker) with Zenhub @gsora @KaloyanTanev @pinebit

**Comment by gsora** [comment]
This is being worked on as we speak: https://github.com/ObolNetwork/lido-charon-distributed-validator-node/pull/64
