### ISSUE TITLE
Show EL + CL container health/readiness on singlenode dashboard

### ISSUE THREAD

**Issue by OisinKyne** [ObolNetwork/charon-distributed-validator-node#36]
# 🚀 Feature Request

## Problem to be solved

Add grafana panel outlining health of beacon nodes and el nodes

## Proposed Solution

If from charon, we can see metrics like the readiness of  upstream beacon nodes, that would be great. Otherwise, expose lighthouse and geth prom metrics endpoints and add them as targets in prometheus.yml and then create a panel that outlines whether each of the EL and  CL return syncing=true or not. 

## Describe alternatives you've considered

Exposing eth2multi metrics that list BN connections and their readiness on charon's prom server.

## Out of Scope

Reworking these panels to be multi CL+EL friendly.

**Comment by OisinKyne** [comment]
This has been half done. CL monitoring was added here https://github.com/ObolNetwork/charon-distributed-validator-node/pull/56

**Comment by dB2510** [comment]
@OisinKyne I have raised a PR for first iteration of EL panels: #77

**Comment by OisinKyne** [comment]
Closed by https://github.com/ObolNetwork/charon-distributed-validator-node/pull/77
