### ISSUE TITLE
Show validator balances

### ISSUE THREAD

**Issue by OisinKyne** [ObolNetwork/charon-distributed-validator-node#46]
# 🚀 Feature Request

## Problem to be solved

Once a validator deposit is recognised, I believe we can query its balance. 

## Proposed Solution

Add a panel that shows each validators short name (like first 7 chars) and their total balance alongside it. Probably think a table of values is easier for now than a line graph, but idk maybe people would prefer the lines.

**Comment by thomasheremans** [comment]
Linked to https://github.com/ObolNetwork/charon/issues/981
