### ISSUE TITLE
Disallow multiple charon nodes pushing node metrics to central monitoring

### ISSUE THREAD

**Issue by xenowits** [ObolNetwork/charon-distributed-validator-node#48]
## Problem to be solved
Currently, if you put a correct`$PROM_REMOTE_WRITE_TOKEN` token inside `prometheus.yaml`, your node will start pushing node metrics. But, this results in multiple nodes sending differing data. As a result, remote grafana write fails which spams the logs.

## Proposed Solution
Disallow multiple charon nodes pushing node metrics to central grafana for now. We can enable it later (see: https://github.com/ObolNetwork/charon-distributed-validator-node/issues/30).

## Describe alternatives you've considered
None

## Out of Scope
None

**Comment by OisinKyne** [comment]
How do you propose we disallow multiple nodes from pushing? Catching the first error and stopping?
