### ISSUE TITLE
Add threshold and peers to validator info panel

### ISSUE THREAD

**Issue by OisinKyne** [ObolNetwork/charon-distributed-validator-node#65]
# 🚀 Feature Request

## Problem to be solved

We have a helpful info panel that shows us things like lock hash, it would be great if it showed us config.operators.length, and config.threshold

## Proposed Solution

Add two new rows to the version table listing `threshold` and `number of operators`

## Describe alternatives you've considered

Making them number fields in grafana, they shouldn't change so I felt that would be overkill and take up too much space

## Out of Scope

Dynamic operator numbers

**Comment by xenowits** [comment]
Metrics for `threshold`, `num_operators` as well as the `peer_name` are already [added](https://github.com/ObolNetwork/charon/pull/1063).

**Comment by xenowits** [comment]
<img width="1854" alt="Screenshot 2022-08-31 at 9 45 18 PM" src="https://user-images.githubusercontent.com/43061995/187728031-d176ded9-52a2-456c-b62f-c0cc33e58ecc.png">

This is how the charon node dashboard looks now!
