### ISSUE TITLE
Purge-db unneccesary

### ISSUE THREAD

**Issue by corverroos** [ObolNetwork/charon-distributed-validator-node#76]
## Problem to solve

Purging lighthouse DB on restart is bad UX since it slows down startup by a lot.

Check point sync is only required if you do not have a DB yet, so I do not think `--purge-db` is required:
 - either you have a DB, then use that and sync from that (purge and checkpoint sync not required)
 - or you do not have DB, then checkpoint-sync, purge not required since DB empty 

## Proposed solution

Remove `--purge-db` flag

**Comment by OisinKyne** [comment]
Will checkpoint sync freak out if there is data already present? not sure it won't error if we remove the flag

**Comment by dB2510** [comment]
resolve by #90
