### ISSUE TITLE
Reduce the prometheus scrape interval

### ISSUE THREAD

**Issue by eth2devops** [ObolNetwork/charon-distributed-validator-node#83]
Grafana cloud billing is based on usage, and usage is determined by two primary factors:

- The number of active series (95th percentile)
- The number of data points per minute (DPM), also at the 95th percentile. 

Illustrative Example for Grafana Cloud Pro:
- Scenario A: 50,000 active series at a 60 second scrape interval (that is, 1 DPM) Pricing: 50,000 active series * (1 DPM / 1 DPM Included) * ($8 / 1000 active series) = $400 / month
- Scenario B: 50,000 active series at a 30 second scrape interval (that is, 2 DPM) Pricing: 50,000 active series* (2 DPM / 1 DPM Included) * ($8 / 1000 active series) = $800 / month

We have to reduce the scrape interval in the `prometheus.yml` configuration from 12s to 384s (1 epoch) in the following repos:
-`charon-distributed-validator-node` and 
-`charon-distributed-validator-cluster`

**Comment by corverroos** [comment]
I'm happy to decrease the default scrape period to 30s. We can then ask users to decrease it further to 1min as part of "Leader Adds Central Monitoring Token"
