### ISSUE TITLE
Configure beaconcha.in URIs with network

### ISSUE THREAD

**Issue by dB2510** [ObolNetwork/charon-distributed-validator-node#86]
# 🚀 Feature Request

## Problem to be solved

Currently the base URL for validator URIs in validators panel is hardcoded to https://goerli.beaconcha.in/validators/ but this will not work for other networks. We need to expose network label to be able to configure beaconcha.in URIs according to network.

## Proposed Solution

Add a network label to `core_scheduler_validator_balance_gwei` in charon. After that update Validators panel to configure URI according to network label.

**Comment by xenowits** [comment]
`cluster_network` is now part of all charon metrics. Moreover, i have replaced the [beaconcha.in](https://beaconcha.in/) links with [goerli.beaconcha.in](https://goerli.beaconcha.in/) as most of our validators are on goerli.

Override data link:
**goerli**
http://${__data.fields.cluster_network}.beaconcha.in/validator/${__data.fields["Public Key"]} 
**mainnet**
http://beaconcha.in/validator/${__data.fields["Public Key"]} 
**gnosis**
https://beacon.gnosischain.com/validator/${__data.fields["Public Key"]}
**ropsten**
The ropsten explorer is broken as of now.
**sepolia**
Explorer for sepolia is not live yet.

This screenshot shows how to add override link:
<img width="1204" alt="Screenshot 2022-11-10 at 2 16 26 PM" src="https://user-images.githubusercontent.com/43061995/201043478-a6727c92-44fe-489e-9d67-bead33960228.png">
