### ISSUE TITLE
Move user configuration to env files

### ISSUE THREAD

**Issue by corverroos** [ObolNetwork/charon-distributed-validator-node#87]
# 🚀 Feature Request

## Problem to be solved

Users are required to modify git-checked-in files in this repo. E.g. adding grafana cloud tokens or standalone bootnodes or voluntary exits.

Modifying git-checked-in results in problems when users want to `git pull` the latest release/version of this repo. They probably need to `git stash` followed by `git stash pop` with merge conflicts. 
 
## Proposed Solution

Move all user configuration to `env` files.
 - Values that can be updated or modified in git-checked-in files should be controlled via env variables.
 - We can still provide defaults for env vars, allowing users to optionally configure some values.

Specifically, we want to have both:
* `services.charon.env_file`: The values in the `.env` override the defaults.
* `services.charon.environment`: These values would act as defaults.

But, since `environment` takes precedence over `env_file`, it is tricky because we want just the opposite.

**Comment by NodesCrew** [comment]
Updated with a full cluster, the network seems to be more stable.

However, I have a question regarding .env.sample. Why couldn't .env.global be made that can be overridden by .env.local?

This way you would solve the problem of new variables that would not need to be added to the local config. And in the current situation, if you add a new variable, we will be forced to edit .env

An example pseudocode might look like this

config = {}
config = config.update(".env.global")
config = config.update(".env.local")

**Comment by hukutu4** [comment]
Totally agree with you, guys. It seems to be very useful.

**Comment by leprick0n** [comment]
That would make sense! And less problems with updates
