### ISSUE TITLE
Port geth and lighthouse

### ISSUE THREAD

**Issue by leprick0n** [ObolNetwork/charon-distributed-validator-node#92]
In the new docker-compose.yml geth and lighthouse use the same ports 30303 ! Because of this the containers do not start ! (The last version of LIGHTHOUSE used port 9000)

**Comment by leprick0n** [comment]
> lighthouse:
    image: sigp/lighthouse:${LIGHTHOUSE_VERSION:-v3.0.0}
    depends_on:
      - geth
    ports:
      - ${LIGHTHOUSE_PORT_P2P:-9000}:9000/tcp   # P2P TCP
      - ${LIGHTHOUSE_PORT_P2P:-9000}:9000/udp   # P2P UDP
      - ${LIGHTHOUSE_PORT_METRICS:-5052}:5052     # Metrics
    command: |

**Comment by ValentinaWave** [comment]
Yes, I had an error with the ports after the update, thank you, I replaced it with 9000, now all the containers are running

**Comment by leprick0n** [comment]
Fixed (гАТовА)) 🙃
